### ISSUE TITLE
Syncing all worlds to the main one

### ISSUE THREAD

**Issue by didkoti** [Harieo/Seasons#41]
One thing that really bothers me is that the worlds aren't synced by time. When players sleep in one world it goes one day ahead of the others :/

**Comment by Harieo** [comment]
This is a normal vanilla Minecraft mechanic and it would require Seasons to edit the normal way Minecraft works to make this happen. I'm reluctant to do this because I don't want the plugin to heavily edit vanilla mechanics lest we risk annoying people who like things the way they are, or have other features which rely on it.

**Comment by didkoti** [comment]
Then I'll have to lookup for a 3rd party plugin that syncs the time between worlds?

**Comment by Harieo** [comment]
> 
> 
> Then I'll have to lookup for a 3rd party plugin that syncs the time between worlds?

I have not decided whether to implement this yet, it will need to be discussed with people on the Discord to see if it's worth doing.

**Comment by Harieo** [comment]
After discussion, we've decided not to implement this feature. This is something for a third-party plugin to handle and it unfortunately goes too far past our policy of not editing vanilla features.
