### ISSUE TITLE
Lang translated to polish

### ISSUE THREAD

**Issue by GrzegorzWalewski** [Harieo/Seasons#48]
Hi, I translated your lang.yml file to polish. It will be awesome if You could add it in plugin so others don't need to do it :D
[lang.yml - polish version](https://drive.google.com/file/d/1uoYAeU44YFxdCJSLkJhc7eDWWRyhBKqK/view?usp=sharing)

**Comment by Harieo** [comment]
I'm having issues downloading your file from Google Drive. Would you be able to send it to me via Discord or email it to me?

**Comment by GrzegorzWalewski** [comment]
Sure, i sent it to business@harieo.net ;)

**Comment by Harieo** [comment]
The developers have had a discussion about this issue and have decided that accepting a single language file would not be maintainable in future updates. The issue we have is that we would need to keep updating language files for every update and without a proper translation team which we could rely on, future updates could be severely hindered. 

We have run messages for translators to join our team but due to a lack of responses, the project failed miserably. This is why we don't support our own translated language files at the moment 😞 

Thank you for contributing though, we appreciate you taking extra effort to help us out 👍🏼
